baseURL = "https://example.com"
defaultContentLanguage = "en"
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
theme = "hugo-scroll"
themesDir = "../.."
title = "#5000 sueños"
[params]
copyright = "© Jane Doe"
description = "Conoce nuestros sueños"
favicon = "images/favicon.png"
images = ["images/cover-image.jpg"]
title = "# Programa 5000 sueños"
[params.meta]
keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"
